FROM node:20 AS build
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/gerardlemetayerc/opentf-server-ui.git /app
WORKDIR /app
RUN npm install
RUN npm run build

FROM nginx:1.25-alpine
# Copier la conf nginx depuis l'image de build
COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]